### ISSUE TITLE
Swingspector not working with Gradle project

### ISSUE THREAD

**Issue by jrobinso** [ohle/Swingspector#33]
Hi,  I added the plugin as instructed,  and its enabled, unfortunately the Swing category does not show up when running from Gradle (see first screenshot).   It does showup from an "Application" run configuration,  however I have never gotten such a configuration to work in a Gradle project.  None of the dependent modules are found.

So I'm stuck.  Any possibility this could work with a Gradle run configuration?  

THanks

<img width="880" alt="Screen Shot 2023-12-12 at 6 58 13 PM" src="https://github.com/ohle/Swingspector/assets/933148/93bf6120-58de-466a-ab30-cb709edb71f2">
<img width="776" alt="Screen Shot 2023-12-12 at 6 58 29 PM" src="https://github.com/ohle/Swingspector/assets/933148/fcc61b5e-b17a-4fdb-b4c4-2a9fd7e3cac4">

**Comment by ohle** [comment]
Could you try installing [this version](https://github.com/ohle/Swingspector/files/13729029/Swingspector-gradle.zip) of the plugin and see if that works?

**Comment by jrobinso** [comment]
Yes, that's working!  Thanks for that, this will be very useful.
